name: ${project.name}
version: ${project.version}-PROTO
description: ${project.description}
authors: [AMGewka, cereal, Sleaker, mung3r]
website: ${project.url}
api-version: 1.13

main: ${mainClass}
load: startup

commands:
  vault-info:
    description: Показывает информацию о Vault
    usage: |
      /<command> - Показывает информацию о Vault
    permission: vault.admin
  vault-convert:
    description: Конвертирует все данные из economy1 и переносит их в economy2
    usage: |
      /<command> [economy1] [economy2]
    permission: vault.admin

permissions:
  vault.admin:
    description: Уведомляет игрока, когда Vault нуждается в обновлении
    default: op
